using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Movement : MonoBehaviour {
	Rigidbody rb;
	public float speed = 2000;
	public float Drag = 1;

	// Use this for initialization
	void Start () {
		rb = GetComponent<Rigidbody> ();
		rb.drag = Drag;
	}
	
	// Update is called once per frame
	void Update () {


		if (Input.GetKey(KeyCode.A)) {
			rb.AddForce (Vector3.left * speed);
		}
		if (Input.GetKey(KeyCode.D)) {
			rb.AddForce (Vector3.right * speed);
		}
		if (Input.GetKey(KeyCode.W)) {
			rb.AddForce (Vector3.up * speed);
		}
		if (Input.GetKey(KeyCode.S)) {
			rb.AddForce (Vector3.down * speed);
		}
	}
}
